// <auto-generated />
namespace WaterAndWastewaterAuthorithy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Water921103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Water921103));
        
        string IMigrationMetadata.Id
        {
            get { return "201401231035520_Water921103"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
