// <auto-generated />
namespace WaterAndWastewaterAuthorithy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Water9211244 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Water9211244));
        
        string IMigrationMetadata.Id
        {
            get { return "201402131000521_Water921124-4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
