// <auto-generated />
namespace WaterAndWastewaterAuthorithy.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Water921116 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Water921116));
        
        string IMigrationMetadata.Id
        {
            get { return "201402051428109_Water921116"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
